mariaDB4j:
  databaseName: myboard
  port: 3306

image:
  default: https://static.productionready.io/images/smiley-cyrus.jpg

jwt:
  secret: nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
  sessionTime: 86400

server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local

  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.hbm2ddl.auto: update
    hibernate:
      ddl-auto: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/myboard?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: slalYlqkf!!!

handlebars:
  enabled: true
  suffix: .html
  prefix: classpath:templates/
